const comfyTemplateOverrides = Object.freeze({
  api_nano_banana_pro: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Image · identity',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Nano Banana Pro won identity preservation in the blind image benchmark.',
    qualityObservation: '8.03/10 weighted; best face, complexion, beauty mark and overall identity continuity.',
    limitation: 'The model is proven through the Runway workspace; the official ComfyUI template still needs an exact-route artifact.',
    benchmark: Object.freeze({ model: 'nano-banana-pro', score: 8.03, specialty: 'identity' }),
  }),
  api_bytedance_seedream_5_0_pro_t2i: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Image · balanced hero shot',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedream 5 won the blind balanced full-body image benchmark.',
    qualityObservation: '8.13/10 weighted; strongest balance of anatomy, full-body composition and costume continuity.',
    limitation: 'The exact Pro template route was not the route used for the benchmark and remains unproven.',
    benchmark: Object.freeze({ model: 'seedream-5', score: 8.13, specialty: 'balanced_full_body' }),
  }),
  api_bytedance_seedream_5_0_pro_image_edit: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Image · generative edit',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The Seedream 5 family won the balanced image benchmark; the official edit template is available.',
    limitation: 'The T2I result does not prove localized edit quality. An exact-route edit artifact is still required.',
  }),
  api_runway_reference_to_image: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Image · dynamic composition',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Runway Gen-4 Image Turbo won dynamism/composition in the blind image benchmark.',
    qualityObservation: '8.10/10 weighted; strongest cinematic motion cues and composition, behind Nano Banana Pro on identity.',
    limitation: 'The exact official ComfyUI template route needs its own artifact receipt.',
    benchmark: Object.freeze({ model: 'gen-4-image-turbo', score: 8.10, specialty: 'dynamic_composition' }),
  }),
  video_wan_animate2: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Video · identity and motion transfer',
    evidenceLevel: 'PRODUCT_PROVEN',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'PRODUCT_PROVEN',
    evidenceLabel: 'The exact official Wan Animate 2 route produced the approved reversible retake, survived cold reopen and exported a verified master.',
    qualityObservation: 'V2 won at reference image strength 1.35 and pose strength 1.25; the approved product uses a face-only reversible patch to preserve body, environment and audio.',
    limitation: 'Full-frame output did not preserve the original background/halo. A compatible external GPU runtime and the sealed model pack are required; no active GPU is assumed.',
    benchmark: Object.freeze({ model: 'wan-animate-2', score: null, specialty: 'identity_motion_transfer' }),
  }),
  api_seedance2_5_i2v_1080p: Object.freeze({
    portfolioRole: 'CHAMPION',
    capabilityLane: 'Video · identity motion',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedance 2.5 won the blind I2V benchmark on a shared 5 s identity-motion brief.',
    qualityObservation: '9.55/10 weighted; preserved face, beauty mark, outfit, anatomy and scene during the controlled turn.',
    limitation: 'The model is product-proven through the Runway workspace; the official ComfyUI template route still requires its own receipt.',
    benchmark: Object.freeze({ model: 'seedance-2.5', score: 9.55, specialty: 'identity_motion' }),
  }),
  api_seedance2_5_t2v: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · text to video',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedance 2.5 is product-proven for I2V and the official T2V route is available.',
    limitation: 'I2V quality does not prove text-to-video behavior. This route still needs a comparable artifact.',
  }),
  api_seedance2_5_t2v_1080p: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · text to video 1080p',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 1080p T2V workflow is discoverable.',
    limitation: 'No exact 1080p T2V artifact has passed the product gate.',
  }),
  api_seedance2_5_flf2v: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · first/last-frame continuity',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 FLF2V workflow is discoverable.',
    limitation: 'No exact first/last-frame continuity artifact has passed the product gate.',
  }),
  api_seedance2_5_r2v: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Video · multimodal reference',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'TECHNICALLY_VALIDATED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedance 2.5 multishot/reference behavior was tested with a real 5 s product artifact.',
    qualityObservation: 'Strong identity and shot-order obedience; continuity of background, lighting and spatial trajectory still needs repair.',
    limitation: 'Use for planned multi-shot generation only with a downstream continuity gate.',
  }),
  api_seedance2_5_video_extend: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · extension',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 video-extension workflow is discoverable.',
    limitation: 'No exact extension artifact has passed continuity and cold-reopen gates.',
  }),
  api_seedance2_5_video_editing: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · generative edit',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 edit workflow is available; the same model family won I2V.',
    qualityObservation: 'No exact edit artifact has passed the product gate yet.',
    limitation: 'Do not inherit the I2V score as proof of editing quality.',
  }),
  api_kling_o3_i2v: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Video · high-motion I2V',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Kling O3 Pro was benchmarked blindly on the common identity-motion brief.',
    qualityObservation: '6.325/10 weighted; strong movement, but it substituted the requested pivot with a jump and changed lighting.',
    limitation: 'Use when motion energy is more important than strict choreography; exact ComfyUI route remains unproven.',
    benchmark: Object.freeze({ model: 'kling-o3-pro', score: 6.325, specialty: 'high_motion' }),
  }),
  api_kling_o3_flf2v: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · first/last-frame premium',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Kling O3 FLF2V workflow is discoverable and the model family was benchmarked.',
    limitation: 'No exact FLF2V artifact has passed the continuity gate.',
  }),
  api_kling_o3_video_edit: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · generative edit premium',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Kling O3 video-edit workflow is discoverable.',
    limitation: 'No exact video-edit artifact has passed the product gate.',
  }),
  api_runway_gen4_turo_image_to_video: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Video · cinematic motion',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Runway Gen-4.5 was benchmarked blindly on the common identity-motion brief.',
    qualityObservation: '5.25/10 weighted on this brief; cinematic movement but identity and wardrobe drifted.',
    limitation: 'The official template targets Gen4 Turbo, while the benchmark used Gen-4.5; route and model evidence remain separate.',
    benchmark: Object.freeze({ model: 'gen-4.5', score: 5.25, specialty: 'cinematic_motion' }),
  }),
  api_ltx2_5_i2v: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Video · audio-video sovereign frontier',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'INSTALLED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official LTX 2.5 workflow is available and the transformer is physically present.',
    limitation: 'Local execution lacks the full official encoder/VAE/upscaler pack; the RunPod credential returned HTTP 403 during the authorized benchmark.',
  }),
  video_ltx2_3_i2v: Object.freeze({
    portfolioRole: 'SOVEREIGN_ALTERNATIVE',
    capabilityLane: 'Video · sovereign I2V',
    evidenceLevel: 'INSTALLED',
    modelEvidenceLevel: 'INSTALLED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'LTX 2.3 all-in-one checkpoint and supporting VAE/upscaler are on the durable volume.',
    limitation: 'No current benchmark artifact was produced because RunPod authentication was externally blocked.',
  }),
  audio_minimax_music_3: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · music',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official editable MiniMax Music 3 workflow is discoverable in the live ComfyUI catalog.',
    limitation: 'No comparative product artifact or authenticated execution route was validated in this phase.',
  }),
  api_elevenlabs_text_to_speech: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Audio · voice',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'ElevenLabs has historical product artifacts and its current entitlement returned HTTP 200 in a read-only preflight on 2026-09-09.',
    limitation: 'Credential authorization does not prove this exact ComfyUI route; it still lacks a current artifact and receipt.',
  }),
  api_elevenlabs_speech_to_speech: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Audio · voice conversion',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The ElevenLabs provider has historical voice product evidence and this official route is discoverable.',
    limitation: 'No exact speech-to-speech receipt was validated with the current credential.',
  }),
  api_elevenlabs_text_to_dialogue: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · dialogue',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The ElevenLabs provider is product-proven and the official dialogue route is discoverable.',
    limitation: 'No exact multi-speaker dialogue artifact passed the product gate.',
  }),
  api_elevenlabs_text_to_sound_effects: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · sound effects',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The ElevenLabs provider is product-proven and the official SFX route is discoverable.',
    limitation: 'No exact SFX artifact passed the product gate with the current credential.',
  }),
  api_elevenlabs_voice_isolation: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · voice isolation',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The ElevenLabs provider is product-proven and the official voice-isolation route is discoverable.',
    limitation: 'No exact isolation artifact passed the product gate.',
  }),
  api_elevenLabs_speech_to_text: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · transcription',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The ElevenLabs provider is product-proven and the official transcription route is discoverable.',
    limitation: 'No exact STT artifact passed the product gate with the current credential.',
  }),
  audio_minimax_music_3: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · music',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official MiniMax Music 3 workflow is discoverable.',
    limitation: 'The Runway music clip is product-proven, but MiniMax Music 3 has no comparable artifact or authenticated route in this phase.',
  }),
  api_sonilo_t2m: Object.freeze({
    portfolioRole: 'ECONOMIC_ALTERNATIVE',
    capabilityLane: 'Audio · music',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Sonilo text-to-music workflow is discoverable.',
    limitation: 'No authenticated comparative artifact was produced in this phase.',
  }),
  api_sonilo_v2m: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · soundtrack',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Sonilo video-to-music workflow is discoverable.',
    limitation: 'No authenticated video-to-music artifact was produced in this phase.',
  }),
  audio_ace_step1_5_xl_turbo: Object.freeze({
    portfolioRole: 'SOVEREIGN_ALTERNATIVE',
    capabilityLane: 'Audio · sovereign music',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official ACE-Step 1.5XL Turbo workflow is discoverable.',
    limitation: 'ACE-Step weights were absent from the certified durable volume; the route is not executable today.',
  }),
  api_heygen_avatar_video: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Avatar · talking presenter',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'HeyGen avatar output exists as historical product evidence and its current entitlement returned HTTP 200 in a read-only preflight on 2026-09-09.',
    limitation: 'Credential authorization does not prove the exact official ComfyUI template; it still needs a current artifact and receipt.',
  }),
  api_heygen_talking_photo: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Avatar · talking photo',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'HeyGen talking-avatar output exists as historical product evidence and its current entitlement returned HTTP 200 in a read-only preflight on 2026-09-09.',
    limitation: 'Credential authorization does not prove the exact official talking-photo route; it still needs a current artifact and receipt.',
  }),
  api_heygen_video_translate: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Avatar · translated performance',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The HeyGen provider is product-proven and the official translation template is discoverable.',
    limitation: 'No exact translated-video artifact has passed the product gate.',
  }),
  api_sync_so_lip_sync_video: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · lipsync',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Sync 3 lipsync workflow is discoverable.',
    limitation: 'No current credential, comparable benchmark or product receipt was validated.',
  }),
  api_sync_so_talking_image: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · talking image lipsync',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Sync 3 talking-image workflow is discoverable.',
    limitation: 'No current credential, comparable benchmark or product receipt was validated.',
  }),
  video_wan2_1_infinitetalk: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · sovereign full-body dubbing',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official InfiniteTalk workflow is discoverable.',
    limitation: 'Durable InfiniteTalk weights and an exact product artifact are absent from the certified runtime.',
  }),
  'templates_liveportrait.app': Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · sovereign facial performance',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official LivePortrait workflow is discoverable.',
    limitation: 'The certified runtime has no validated LivePortrait execution pack or product artifact.',
  }),
  '3d_pixal3d_trellis2_image_to_model': Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: '3D · image to model',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Pixal3D + TRELLIS.2 editable workflow is discoverable.',
    limitation: 'TRELLIS.2 weights and a product artifact are absent from the durable runtime.',
  }),
  api_bria_remove_video_background: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'VFX · video matte',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'A real transparent video matte was produced and verified during the benchmark.',
    qualityObservation: 'Alpha was genuine; temporal hair, hand and skirt edges were unstable.',
    limitation: 'Useful as an auxiliary matte only until an exact-route continuity repair passes the product gate.',
    benchmark: Object.freeze({ model: 'runway-remove-background', score: null, specialty: 'auxiliary_matte' }),
  }),
  api_bria_video_green_screen: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'VFX · green screen',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The matte model class produced a real alpha artifact; the official green-screen route is discoverable.',
    limitation: 'Do not inherit the matte artifact as proof of green-screen edge quality.',
  }),
  api_bria_video_replace_background: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'VFX · background replacement',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The matte model class produced a real alpha artifact; the official replacement route is discoverable.',
    limitation: 'No exact replacement artifact has passed temporal-edge and composition gates.',
  }),
  api_bria_eraser: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'VFX · object removal',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Bria eraser workflow is discoverable.',
    limitation: 'No exact object-removal artifact has passed the product gate.',
  }),
  api_bria_genfill: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'VFX · inpainting',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Bria generative-fill workflow is discoverable.',
    limitation: 'No exact inpaint artifact has passed the product gate.',
  }),
  api_beeble_switchx_image_edit: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'VFX · relighting',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official SwitchX relighting workflow is discoverable.',
    limitation: 'No exact relighting artifact has passed the product gate.',
  }),
  api_topaz_astra2: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Finishing · premium upscale',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Topaz Astra 2 workflow is discoverable.',
    limitation: 'The tested generic 4K upscaler increased resolution but was rejected for premium finishing; Astra 2 itself remains unbenchmarked.',
  }),
  api_topaz_video_enhance: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Finishing · video upscale',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Topaz Astra Fast workflow is discoverable and also exposed by the guided Velorn catalog.',
    limitation: 'No exact Astra Fast artifact has passed the product gate.',
  }),
  api_topaz_starlight_precise25: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Finishing · restoration upscale',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Topaz Starlight Precise 2.5 workflow is discoverable.',
    limitation: 'No exact Starlight artifact has passed the product gate.',
  }),
  api_bytedance_vcube_video_enhance: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Finishing · video enhance',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official ByteDance vCube workflow is discoverable.',
    limitation: 'No comparative artifact has passed the product gate.',
  }),
  api_wavespeed_flshvsr_video_upscale: Object.freeze({
    portfolioRole: 'ECONOMIC_ALTERNATIVE',
    capabilityLane: 'Finishing · fast upscale',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official FlashVSR cloud workflow is discoverable.',
    limitation: 'No exact FlashVSR artifact has passed the product gate.',
  }),
  utility_video_frame_interpolation: Object.freeze({
    portfolioRole: 'SOVEREIGN_ALTERNATIVE',
    capabilityLane: 'Finishing · frame interpolation',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'INSTALLED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'RIFE 4.26 assets are installed, but the exact official workflow references FILM model film_net_fp16.safetensors.',
    limitation: 'FILM weights were not found in the certified durable volume; RIFE requires a separate exact graph and product artifact.',
  }),
  'utility-frame_interpolation-film': Object.freeze({
    portfolioRole: 'SOVEREIGN_ALTERNATIVE',
    capabilityLane: 'Finishing · frame interpolation',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official FILM interpolation workflow is discoverable.',
    limitation: 'FILM weights and an exact product artifact were not certified on the durable volume.',
  }),
  utility_gimm_frame_interpolation: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Finishing · frame interpolation',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official GIMM-VFI interpolation workflow is discoverable.',
    limitation: 'No installed weights or product artifact were certified.',
  }),
  'utility-gan_upscaler': Object.freeze({
    portfolioRole: 'SOVEREIGN_ALTERNATIVE',
    capabilityLane: 'Finishing · deterministic upscale',
    evidenceLevel: 'INSTALLED',
    evidenceLabel: 'Real-ESRGAN-family upscaler assets are present on the durable volume.',
    limitation: 'The exact official template has not passed a current product gate.',
  }),
  utility_seedvr2_video_upscale: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Finishing · generative restoration',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official SeedVR2 video-upscale workflow is discoverable.',
    limitation: 'SeedVR2 weights were not certified on the durable volume.',
  }),
  utility_image_upscale_supir: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Finishing · image restoration',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official SUPIR restoration workflow is discoverable.',
    limitation: 'SUPIR weights and a product artifact were not certified on the durable volume.',
  }),
  api_meshy7_image_to_model: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: '3D · image to model',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Meshy 7 image-to-3D workflow is discoverable and a Meshy credential exists in the ecosystem.',
    limitation: 'No comparable 3D artifact was produced within the authorized benchmark budget.',
  }),
  api_meshy7_text_to_model: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: '3D · text to model',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Meshy 7 text-to-3D workflow is discoverable.',
    limitation: 'No comparable 3D artifact was produced within the authorized benchmark budget.',
  }),
  api_hunyuan3d_image_to_model: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: '3D · image to model',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Hunyuan3D API workflow is discoverable.',
    limitation: 'No authenticated artifact passed the product gate.',
  }),
  '3d_hunyuan3d-v2.1': Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: '3D · sovereign image to model',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Hunyuan3D 2.1 local workflow is discoverable.',
    limitation: 'Durable Hunyuan3D weights and a validated runtime pack are absent.',
  }),
  utility_sam3d_body: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: '3D · body mesh',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official SAM 3D Body workflow is discoverable.',
    limitation: 'SAM 3D weights are absent from the certified durable volume.',
  }),
  api_bria_remove_video_background_transparent: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'VFX · video matte',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'A real transparent video matte was produced and its alpha channel verified.',
    qualityObservation: 'The route preserves a usable alpha channel but exhibits temporally unstable fine edges.',
    limitation: 'The benchmark proves the provider capability, not the exact official Bria template route; use as an auxiliary matte pending repair.',
    benchmark: Object.freeze({ model: 'runway-remove-background', score: null, specialty: 'transparent_matte' }),
  }),
})

module.exports = Object.freeze({ comfyTemplateOverrides })
