const comfyTemplateOverrides = Object.freeze({
  api_nano_banana_pro: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Image · identity',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Nano Banana Pro won identity preservation in the blind image benchmark.',
    qualityObservation: '8.03/10 weighted; best face, complexion, beauty mark and overall identity continuity.',
    limitation: 'The model is proven through the Runway workspace; the official ComfyUI template still needs an exact-route artifact.',
    benchmark: Object.freeze({ model: 'nano-banana-pro', score: 8.03, specialty: 'identity' }),
  }),
  api_bytedance_seedream_5_0_pro_t2i: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Image · balanced hero shot',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedream 5 won the blind balanced full-body image benchmark.',
    qualityObservation: '8.13/10 weighted; strongest balance of anatomy, full-body composition and costume continuity.',
    limitation: 'The exact Pro template route was not the route used for the benchmark and remains unproven.',
    benchmark: Object.freeze({ model: 'seedream-5', score: 8.13, specialty: 'balanced_full_body' }),
  }),
  api_bytedance_seedream_5_0_pro_image_edit: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Image · generative edit',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The Seedream 5 family won the balanced image benchmark; the official edit template is available.',
    limitation: 'The T2I result does not prove localized edit quality. An exact-route edit artifact is still required.',
  }),
  api_runway_reference_to_image: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Image · dynamic composition',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Runway Gen-4 Image Turbo won dynamism/composition in the blind image benchmark.',
    qualityObservation: '8.10/10 weighted; strongest cinematic motion cues and composition, behind Nano Banana Pro on identity.',
    limitation: 'The exact official ComfyUI template route needs its own artifact receipt.',
    benchmark: Object.freeze({ model: 'gen-4-image-turbo', score: 8.10, specialty: 'dynamic_composition' }),
  }),
  api_seedance2_5_i2v_1080p: Object.freeze({
    portfolioRole: 'CHAMPION',
    capabilityLane: 'Video · identity motion',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedance 2.5 won the blind I2V benchmark on a shared 5 s identity-motion brief.',
    qualityObservation: '9.55/10 weighted; preserved face, beauty mark, outfit, anatomy and scene during the controlled turn.',
    limitation: 'The model is product-proven through the Runway workspace; the official ComfyUI template route still requires its own receipt.',
    benchmark: Object.freeze({ model: 'seedance-2.5', score: 9.55, specialty: 'identity_motion' }),
  }),
  api_seedance2_5_t2v: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · text to video',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedance 2.5 is product-proven for I2V and the official T2V route is available.',
    limitation: 'I2V quality does not prove text-to-video behavior. This route still needs a comparable artifact.',
  }),
  api_seedance2_5_t2v_1080p: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · text to video 1080p',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 1080p T2V workflow is discoverable.',
    limitation: 'No exact 1080p T2V artifact has passed the product gate.',
  }),
  api_seedance2_5_flf2v: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · first/last-frame continuity',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 FLF2V workflow is discoverable.',
    limitation: 'No exact first/last-frame continuity artifact has passed the product gate.',
  }),
  api_seedance2_5_r2v: Object.freeze({
    portfolioRole: 'SPECIALIST_CHAMPION',
    capabilityLane: 'Video · multimodal reference',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'TECHNICALLY_VALIDATED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Seedance 2.5 multishot/reference behavior was tested with a real 5 s product artifact.',
    qualityObservation: 'Strong identity and shot-order obedience; continuity of background, lighting and spatial trajectory still needs repair.',
    limitation: 'Use for planned multi-shot generation only with a downstream continuity gate.',
  }),
  api_seedance2_5_video_extend: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · extension',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 video-extension workflow is discoverable.',
    limitation: 'No exact extension artifact has passed continuity and cold-reopen gates.',
  }),
  api_seedance2_5_video_editing: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · generative edit',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Seedance 2.5 edit workflow is available; the same model family won I2V.',
    qualityObservation: 'No exact edit artifact has passed the product gate yet.',
    limitation: 'Do not inherit the I2V score as proof of editing quality.',
  }),
  api_kling_o3_i2v: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Video · high-motion I2V',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Kling O3 Pro was benchmarked blindly on the common identity-motion brief.',
    qualityObservation: '6.325/10 weighted; strong movement, but it substituted the requested pivot with a jump and changed lighting.',
    limitation: 'Use when motion energy is more important than strict choreography; exact ComfyUI route remains unproven.',
    benchmark: Object.freeze({ model: 'kling-o3-pro', score: 6.325, specialty: 'high_motion' }),
  }),
  api_kling_o3_flf2v: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · first/last-frame premium',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Kling O3 FLF2V workflow is discoverable and the model family was benchmarked.',
    limitation: 'No exact FLF2V artifact has passed the continuity gate.',
  }),
  api_kling_o3_video_edit: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Video · generative edit premium',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Kling O3 video-edit workflow is discoverable.',
    limitation: 'No exact video-edit artifact has passed the product gate.',
  }),
  api_runway_gen4_turo_image_to_video: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Video · cinematic motion',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Runway Gen-4.5 was benchmarked blindly on the common identity-motion brief.',
    qualityObservation: '5.25/10 weighted on this brief; cinematic movement but identity and wardrobe drifted.',
    limitation: 'The official template targets Gen4 Turbo, while the benchmark used Gen-4.5; route and model evidence remain separate.',
    benchmark: Object.freeze({ model: 'gen-4.5', score: 5.25, specialty: 'cinematic_motion' }),
  }),
  api_ltx2_5_i2v: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Video · audio-video sovereign frontier',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'INSTALLED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official LTX 2.5 workflow is available and the transformer is physically present.',
    limitation: 'Local execution lacks the full official encoder/VAE/upscaler pack; the RunPod credential returned HTTP 403 during the authorized benchmark.',
  }),
  video_ltx2_3_i2v: Object.freeze({
    portfolioRole: 'SOVEREIGN_ALTERNATIVE',
    capabilityLane: 'Video · sovereign I2V',
    evidenceLevel: 'INSTALLED',
    modelEvidenceLevel: 'INSTALLED',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'LTX 2.3 all-in-one checkpoint and supporting VAE/upscaler are on the durable volume.',
    limitation: 'No current benchmark artifact was produced because RunPod authentication was externally blocked.',
  }),
  audio_minimax_music_3: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Audio · music',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official editable MiniMax Music 3 workflow is discoverable in the live ComfyUI catalog.',
    limitation: 'No comparative product artifact or authenticated execution route was validated in this phase.',
  }),
  api_elevenlabs_text_to_speech: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Audio · voice',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'ElevenLabs has historical product artifacts in the ecosystem.',
    limitation: 'The current sandbox credential returned HTTP 401 and this exact ComfyUI route remains unproven.',
  }),
  api_heygen_avatar_video: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Avatar · talking presenter',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'HeyGen avatar output exists as historical product evidence.',
    limitation: 'The exact official ComfyUI template route needs a current authenticated artifact.',
  }),
  api_heygen_talking_photo: Object.freeze({
    portfolioRole: 'PREMIUM_ALTERNATIVE',
    capabilityLane: 'Avatar · talking photo',
    evidenceLevel: 'TECHNICALLY_VALIDATED',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'HeyGen talking-avatar output exists as historical product evidence.',
    limitation: 'The exact official ComfyUI talking-photo route needs a current authenticated artifact.',
  }),
  api_heygen_video_translate: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Avatar · translated performance',
    evidenceLevel: 'DISCOVERABLE',
    modelEvidenceLevel: 'PRODUCT_PROVEN',
    routeEvidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'The HeyGen provider is product-proven and the official translation template is discoverable.',
    limitation: 'No exact translated-video artifact has passed the product gate.',
  }),
  api_sync_so_lip_sync_video: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · lipsync',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Sync 3 lipsync workflow is discoverable.',
    limitation: 'No current credential, comparable benchmark or product receipt was validated.',
  }),
  api_sync_so_talking_image: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · talking image lipsync',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Sync 3 talking-image workflow is discoverable.',
    limitation: 'No current credential, comparable benchmark or product receipt was validated.',
  }),
  video_wan2_1_infinitetalk: Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · sovereign full-body dubbing',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official InfiniteTalk workflow is discoverable.',
    limitation: 'Durable InfiniteTalk weights and an exact product artifact are absent from the certified runtime.',
  }),
  'templates_liveportrait.app': Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: 'Avatar · sovereign facial performance',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official LivePortrait workflow is discoverable.',
    limitation: 'The certified runtime has no validated LivePortrait execution pack or product artifact.',
  }),
  '3d_pixal3d_trellis2_image_to_model': Object.freeze({
    portfolioRole: 'FRONTIER_BLOCKED',
    capabilityLane: '3D · image to model',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Pixal3D + TRELLIS.2 editable workflow is discoverable.',
    limitation: 'TRELLIS.2 weights and a product artifact are absent from the durable runtime.',
  }),
  api_topaz_astra2: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'Finishing · premium upscale',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official Topaz Astra 2 workflow is discoverable.',
    limitation: 'The tested generic 4K upscaler increased resolution but was rejected for premium finishing; Astra 2 itself remains unbenchmarked.',
  }),
  api_bria_remove_video_background_transparent: Object.freeze({
    portfolioRole: 'FRONTIER_CANDIDATE',
    capabilityLane: 'VFX · video matte',
    evidenceLevel: 'DISCOVERABLE',
    evidenceLabel: 'Official transparent-background Bria workflow is discoverable.',
    limitation: 'The tested Runway matte preserved alpha but showed temporally unstable hair, hand and skirt edges; Bria remains unbenchmarked.',
  }),
})

module.exports = Object.freeze({ comfyTemplateOverrides })
